info:
  per:
    #Simple properties
    id: 101
    name: raja
    address: hyd
    #Array
    marks1:
    - 30
    - 40
    - 50
    #List
    marks2:
    - 40
    - 50
    - 60
    #set
    marks3:
    - 50
    - 60
    - 70
    #Map
    phones:
      residence: 9999999
      office: 888888
      personal: 777777
    #Reference Type
    job:
      desg: Manager
      salary: 783423.3
      company: HCL
      skills:
      - Java
      - Spring
      - Hibernate
      - J2EE
      